#!/usr/bin/env bash

# bar settings
spacebar -m config status_bar_text_font         "Fantasque Sans Mono:Bold:12.0"
spacebar -m config status_bar_icon_font         "Font Awesome 5 Pro:Regular:12.0"
spacebar -m config status_bar_background_color  0xff202020
spacebar -m config status_bar_foreground_color  0xffa8a8a8
spacebar -m config status_bar_space_icon_strip  1 2 3 4 5 6 7 8 9 10
spacebar -m config status_bar_power_icon_strip   
spacebar -m config status_bar_space_icon        
spacebar -m config status_bar_clock_icon        
spacebar -m config status_bar_clock_format      "%b %d -- %a %-I:%M"

