# Helper functions to simplify connecting to RM/R-SCM devices and access BMCs behind these devices
# The password bypass method was taken from the following links
# * https://www.exratione.com/2014/08/bash-script-ssh-automation-without-a-password-prompt/
# * https://github.com/huan/sshpass.sh/blob/master/sshpass.sh

alias rm_ssh="SSH_ASKPASS_REQUIRE=\"force\" SSH_ASKPASS=~/.rm-pass ssh ${RM_SSH_OPS[@]} -o ServerAliveInterval=60 -c aes256-cbc"

RM_SSH_OPS=("-oLogLevel=error")
RM_SSH_OPS+=("-oStrictHostKeyChecking=no")
RM_SSH_OPS+=("-oUserKnownHostsFile=/dev/null")
RM_SSH_OPS+=("-caes256-cbc,aes256-ctr")

ssh-rm() {
	gum log --time rfc822 --level info -- "SSH_ASKPASS_REQUIRE=\"force\" SSH_ASKPASS=~/.rm-pass ssh ${RM_SSH_OPS[@]} root@${1} ${@:2}"
	SSH_ASKPASS_REQUIRE="force" SSH_ASKPASS=~/.rm-pass ssh ${RM_SSH_OPS[@]} root@${1} ${@:2}
	# sshpass -f ~/.rm-pass ssh ${RM_SSH_OPS[@]} -c aes256-cbc root@${1} ${@:2}
}

ssh-port-tunnelling() {
	# implement port tunnelling
}

change-rm-password() {
	if (( $# == 1 )); then
		cat >~/.rm-pass <<EOF
#!/bin/bash
echo "${1}"
EOF
		chmod +x ~/.rm-pass
	else
		echo "Usage: change-rm-password <password>"
	fi
}

change-bmc-password() {
	local askpass_file="${SSH_ASKPASS_FILE:-$HOME/.bmc-pass}"
	if (( $# == 1 )); then
		echo "change-bmc-password: $1 -> ${askpass_file}"
		touch ${askpass_file}
		cat > ${askpass_file} <<EOF
#!/bin/bash
echo "${1}"
EOF
		chmod +x ${askpass_file}
	else
		echo "Usage: change-bmc-password <password>"
	fi
}

change-bmc-password-su() {
	SSH_ASKPASS_FILE="$HOME/.bmc-pass-su" change-bmc-password ${@}
}

clean_control_chars() {
    while IFS= read -r line; do
        # remove KNOWN control characters. Leave the rest for now.
        # line=$(echo "${line}" | sed 's/\^\[\[K//g')  # unkown control character: ^[[K
        # line=$(echo "${line}" | sed 's/\^\[\[[0-9]\+[P]//g')  # these are generated by up/down completion - e.g. ^[[2P
        line=$(echo "${line}" | sed 's/\^\[\[[0-9]*[A-Z]//g')  # all other ^[[..
        # replay character deletions (backspaces)
        while [[ $(echo "${line}" | grep -E --color=never '.\^H') != "" ]]; do
            line=$(echo "${line}" | sed 's/.\^H//')
        done
        # remove common control characters
        line=$(echo "${line}" | sed 's/\^M$//')  # remove end of line marker from end
        line=$(echo "${line}" | sed 's/^\^G//g')  # remove start marker from start
        # remove ^G from other locations - possibly a good idea
        # line=$(echo "${line}" | sed 's/\^G//g')
        # remove all other control characters - not recommended (many like ^C and ^M indicate which section was processed/ ignored)
        # line=$(echo "${line}" | sed 's/\^[A-Z]//g')
        echo ${line};
    done
}

filter_output() {
    while IFS= read -r line; do
        # convert nonprinting characters and filter out non-prompt (in Ubuntu 14.04 tests, ^G indicates prompt start)
        line=$(echo "${line}" | cat -v | grep -Eo '[\^][G].*[\$#].*')
        [[ ${line} != "" ]] && echo "${line}"
    done
}


format_line() {
    declare -r TAB=$'\t'
    declare -r description="sshlog-${$} ${@}"

    while IFS= read -r line; do
        raw=${line};
        line=$(echo "${line}" | clean_control_chars);
        prompt=$(echo "${line}" | grep -Po '^.*?(\$|#)[\s]*')
        command=${line:${#prompt}}
        timestamp=`date +"%Y-%m-%d %H:%M:%S %z"`
        echo -e "${timestamp}${TAB}${description}${TAB}${prompt}${TAB}${command}"
    done
}

ssh-bmc() {
	local port=22
	local host="localhost"
	local username="${SSH_USERNAME:-admin}"
	local askpass_file="${SSH_ASKPASS_FILE:-$HOME/.bmc-pass}"

	if (( $# == 1 )); then
		 case $1 in
			(*[^0-9]*) 
				host=$1
				;;
			(*)        
				port=$1
				;;
		esac
		shift
	elif (( $# >= 2 )); then
		case $1 in
			(*[^0-9]*) 
				host=$1
				port=$2
				shift
				shift
				;;
			(*)        
				port=$1
				shift
				;;
		esac
	fi
	if [[ -z "$LOG_FILE" ]]; then
		gum log --time rfc822 --level info -- "SSH_ASKPASS_REQUIRE=\"force\" SSH_ASKPASS=${askpass_file} ssh -p ${port} ${RM_SSH_OPS[@]} ${username}@${host} ${@}"
		SSH_ASKPASS_REQUIRE="force" SSH_ASKPASS=${askpass_file} ssh -p ${port} ${RM_SSH_OPS[@]} ${username}@${host} ${@}
	else
		echo "[START]" | format_line >> ${LOG_FILE}
		gum log --time rfc822 --level info -- "SSH_ASKPASS_REQUIRE=\"force\" SSH_ASKPASS=${askpass_file} ssh -p ${port} ${RM_SSH_OPS[@]} ${username}@${host} ${@}"
		SSH_ASKPASS_REQUIRE="force" SSH_ASKPASS=${askpass_file} ssh -p ${port} ${RM_SSH_OPS[@]} ${username}@${host} ${@} | tee >(filter_output | format_line >> ${LOG_FILE})
		echo "[END]" | format_line >> ${LOG_FILE}
	fi
}

ssh-bmc-su() {
	SSH_USERNAME="root" SSH_ASKPASS_FILE="$HOME/.bmc-pass-su" ssh-bmc ${@}
}

scp-bmc() {
	local port=22
	local host="localhost"
	local askpass_file="${SSH_ASKPASS_FILE:-$HOME/.bmc-pass}"

	if (( $# == 1 )); then
		 case $1 in
			(*[^0-9]*) 
				host=$1
				;;
			(*)        
				port=$1
				;;
		esac
		shift
	elif (( $# >= 2 )); then
		case $1 in
			(*[^0-9]*) 
				host=$1
				port=$2
				shift
				shift
				;;
			(*)        
				port=$1
				shift
				;;
		esac
	fi
	gum log --time rfc822 --level info -- "SSH_ASKPASS_REQUIRE=\"force\" SSH_ASKPASS=${askpass_file} scp -P ${port} ${RM_SSH_OPS[@]} ${@}"
	SSH_ASKPASS_REQUIRE="force" SSH_ASKPASS=${askpass_file} scp -P ${port} ${RM_SSH_OPS[@]} ${@}
}

scp-bmc-su() {
	SSH_ASKPASS_FILE="$HOME/.bmc-pass-su" scp-bmc ${@}
}

sftp-rm() {
	SSH_ASKPASS_REQUIRE="force" SSH_ASKPASS=~/.rm-pass sftp ${RM_SSH_OPS[@]} root@${1} ${@:2}
}

ip2dec () {
    local a b c d ip=$@
    IFS=. read -r a b c d <<< "$ip"
    printf '%d\n' "$((a * 256 ** 3 + b * 256 ** 2 + c * 256 + d))"
}

rmPortForward() {
	local rm_host=$1
	local blade_id=$2
	local blade_ip="172.17.0.$(($blade_id*4-3))"
	local ssh_port=$((2022 + ($blade_id - 1)*100))
	local https_port=$((2443 + ($blade_id - 1)*100))
	local args=()
	local remote_ssh_port=22
	if (( $# == 3 )); then
		remote_ssh_port=$3
	fi

	local session_file="/tmp/rm_tunnel_session_$(ip2dec $rm_host)_$ssh_port"
	if [ -S $session_file ]; then
		# ask the user before closing the terminal
		gum confirm "Close existing tunnel" || return

		gum log --time rfc822 --level info -- "Closing existing tunnel... $(cat ${session_file}.args)"
		ssh -S $session_file -O exit $rm_host
		rm -rf ${session_file}.args
	else
		gum log --time rfc822 --level info "Opening new tunnel..."

		args+=("-L$ssh_port:$blade_ip:$remote_ssh_port")
		args+=("-L$https_port:$blade_ip:443")
		# args+=("-L8222:$blade_ip:8222")
		# args+=("-L2200:$blade_ip:2200")

		gum log --time rfc822 --level info -- "Port Forward Map" "$remote_ssh_port -> $ssh_port" "443 -> $https_port"
		echo "${@}" > ${session_file}.args
		gum log --time rfc822 --level info -- "SSH_ASKPASS_REQUIRE=\"force\" SSH_ASKPASS=~/.rm-pass ssh ${RM_SSH_OPS[@]} -f -N -M -S \
			/tmp/rm_tunnel_session_$(ip2dec $rm_host)_$ssh_port ${args[@]} root@${rm_host}"
		SSH_ASKPASS_REQUIRE="force" SSH_ASKPASS=~/.rm-pass ssh ${RM_SSH_OPS[@]} -f -N -M -S \
			/tmp/rm_tunnel_session_$(ip2dec $rm_host)_$ssh_port ${args[@]} root@${rm_host}
	fi
}
